# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

findgrid <- function(cluster_info, k, nobs, ndims) {
    .Call('_GridOnClusters_findgrid', PACKAGE = 'GridOnClusters', cluster_info, k, nobs, ndims)
}

